/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PriceDetails = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'vwap' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
});
export const CandlestickPattern = IDL.Record({
  'wick_low' : IDL.Float64,
  'patternType' : IDL.Text,
  'wick_high' : IDL.Float64,
  'price' : IDL.Float64,
});
export const CEPEData = IDL.Record({
  'oi' : IDL.Float64,
  'doi' : IDL.Float64,
  'strike' : IDL.Text,
  'trend' : IDL.Text,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const ScenarioTags = IDL.Record({
  'trending' : IDL.Bool,
  'pcr_tested' : IDL.Bool,
  'high_oi' : IDL.Bool,
  'reversal' : IDL.Bool,
});
export const OptionChainEntry = IDL.Record({
  'atm' : IDL.Float64,
  'ce_atm_data' : CEPEData,
  'scenarios' : ScenarioTags,
  'pe_atm_data' : CEPEData,
  'price' : PriceDetails,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToWatchlist' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bearishScanner' : IDL.Func([IDL.Text], [PriceDetails], ['query']),
  'bullishScanner' : IDL.Func([IDL.Text], [PriceDetails], ['query']),
  'getAllMarketData' : IDL.Func([], [IDL.Vec(PriceDetails)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandlestickPattern' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CandlestickPattern)],
      ['query'],
    ),
  'getMarketData' : IDL.Func([IDL.Text], [PriceDetails], ['query']),
  'getOptionChainData' : IDL.Func([IDL.Text], [OptionChainEntry], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatchlist' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PriceDetails = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'vwap' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text });
  const CandlestickPattern = IDL.Record({
    'wick_low' : IDL.Float64,
    'patternType' : IDL.Text,
    'wick_high' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const CEPEData = IDL.Record({
    'oi' : IDL.Float64,
    'doi' : IDL.Float64,
    'strike' : IDL.Text,
    'trend' : IDL.Text,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const ScenarioTags = IDL.Record({
    'trending' : IDL.Bool,
    'pcr_tested' : IDL.Bool,
    'high_oi' : IDL.Bool,
    'reversal' : IDL.Bool,
  });
  const OptionChainEntry = IDL.Record({
    'atm' : IDL.Float64,
    'ce_atm_data' : CEPEData,
    'scenarios' : ScenarioTags,
    'pe_atm_data' : CEPEData,
    'price' : PriceDetails,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToWatchlist' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bearishScanner' : IDL.Func([IDL.Text], [PriceDetails], ['query']),
    'bullishScanner' : IDL.Func([IDL.Text], [PriceDetails], ['query']),
    'getAllMarketData' : IDL.Func([], [IDL.Vec(PriceDetails)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandlestickPattern' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CandlestickPattern)],
        ['query'],
      ),
    'getMarketData' : IDL.Func([IDL.Text], [PriceDetails], ['query']),
    'getOptionChainData' : IDL.Func([IDL.Text], [OptionChainEntry], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatchlist' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };