/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PriceDetails = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'vwap' : IDL.Float64,
});
export const CandlestickPattern = IDL.Record({
  'wick_low' : IDL.Float64,
  'patternType' : IDL.Text,
  'wick_high' : IDL.Float64,
  'price' : IDL.Float64,
});
export const MarketSymbolData = IDL.Record({
  'oi' : IDL.Nat,
  'lastPrice' : IDL.Float64,
  'volume' : IDL.Nat,
  'changePercent' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const CEPEData = IDL.Record({
  'oi' : IDL.Float64,
  'doi' : IDL.Float64,
  'strike' : IDL.Text,
  'trend' : IDL.Text,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const ScenarioTags = IDL.Record({
  'trending' : IDL.Bool,
  'pcr_tested' : IDL.Bool,
  'high_oi' : IDL.Bool,
  'reversal' : IDL.Bool,
});
export const OptionChainEntry = IDL.Record({
  'atm' : IDL.Float64,
  'ce_atm_data' : CEPEData,
  'scenarios' : ScenarioTags,
  'pe_atm_data' : CEPEData,
  'price' : PriceDetails,
  'symbol' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
});
export const IndicesSnapshot = IDL.Record({
  'oi' : IDL.Nat,
  'lastPrice' : IDL.Float64,
  'name' : IDL.Text,
  'volume' : IDL.Nat,
  'changePercent' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToWatchlist' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bearishScanner' : IDL.Func([IDL.Text], [PriceDetails], ['query']),
  'bullishScanner' : IDL.Func([IDL.Text], [PriceDetails], ['query']),
  'getAllCandlestickPatterns' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, CandlestickPattern))],
      ['query'],
    ),
  'getAllMarketData' : IDL.Func([], [IDL.Vec(PriceDetails)], ['query']),
  'getAllMarketSymbols' : IDL.Func([], [IDL.Vec(MarketSymbolData)], ['query']),
  'getAllOpenHighScannerData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PriceDetails))],
      ['query'],
    ),
  'getAllOpenLowScannerData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, PriceDetails))],
      ['query'],
    ),
  'getAllOptionChainData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, OptionChainEntry))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandlestickPattern' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CandlestickPattern)],
      ['query'],
    ),
  'getIndicesSnapshot' : IDL.Func([], [IDL.Vec(IndicesSnapshot)], ['query']),
  'getMarketData' : IDL.Func([IDL.Text], [PriceDetails], ['query']),
  'getMarketSnapshot' : IDL.Func([], [IDL.Vec(MarketSymbolData)], ['query']),
  'getMarketSymbolData' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MarketSymbolData)],
      ['query'],
    ),
  'getOptionChain' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getOptionChainData' : IDL.Func([IDL.Text], [OptionChainEntry], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatchlist' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'refreshMarketData' : IDL.Func([], [IDL.Text], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMarketSymbolData' : IDL.Func([IDL.Text, MarketSymbolData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PriceDetails = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'vwap' : IDL.Float64,
  });
  const CandlestickPattern = IDL.Record({
    'wick_low' : IDL.Float64,
    'patternType' : IDL.Text,
    'wick_high' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const MarketSymbolData = IDL.Record({
    'oi' : IDL.Nat,
    'lastPrice' : IDL.Float64,
    'volume' : IDL.Nat,
    'changePercent' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const CEPEData = IDL.Record({
    'oi' : IDL.Float64,
    'doi' : IDL.Float64,
    'strike' : IDL.Text,
    'trend' : IDL.Text,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const ScenarioTags = IDL.Record({
    'trending' : IDL.Bool,
    'pcr_tested' : IDL.Bool,
    'high_oi' : IDL.Bool,
    'reversal' : IDL.Bool,
  });
  const OptionChainEntry = IDL.Record({
    'atm' : IDL.Float64,
    'ce_atm_data' : CEPEData,
    'scenarios' : ScenarioTags,
    'pe_atm_data' : CEPEData,
    'price' : PriceDetails,
    'symbol' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text });
  const IndicesSnapshot = IDL.Record({
    'oi' : IDL.Nat,
    'lastPrice' : IDL.Float64,
    'name' : IDL.Text,
    'volume' : IDL.Nat,
    'changePercent' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToWatchlist' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bearishScanner' : IDL.Func([IDL.Text], [PriceDetails], ['query']),
    'bullishScanner' : IDL.Func([IDL.Text], [PriceDetails], ['query']),
    'getAllCandlestickPatterns' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, CandlestickPattern))],
        ['query'],
      ),
    'getAllMarketData' : IDL.Func([], [IDL.Vec(PriceDetails)], ['query']),
    'getAllMarketSymbols' : IDL.Func(
        [],
        [IDL.Vec(MarketSymbolData)],
        ['query'],
      ),
    'getAllOpenHighScannerData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PriceDetails))],
        ['query'],
      ),
    'getAllOpenLowScannerData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, PriceDetails))],
        ['query'],
      ),
    'getAllOptionChainData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, OptionChainEntry))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandlestickPattern' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CandlestickPattern)],
        ['query'],
      ),
    'getIndicesSnapshot' : IDL.Func([], [IDL.Vec(IndicesSnapshot)], ['query']),
    'getMarketData' : IDL.Func([IDL.Text], [PriceDetails], ['query']),
    'getMarketSnapshot' : IDL.Func([], [IDL.Vec(MarketSymbolData)], ['query']),
    'getMarketSymbolData' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MarketSymbolData)],
        ['query'],
      ),
    'getOptionChain' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getOptionChainData' : IDL.Func([IDL.Text], [OptionChainEntry], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatchlist' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'refreshMarketData' : IDL.Func([], [IDL.Text], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMarketSymbolData' : IDL.Func([IDL.Text, MarketSymbolData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };