/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CEPEData {
  'oi' : number,
  'doi' : number,
  'strike' : string,
  'trend' : string,
  'price' : number,
  'symbol' : string,
}
export interface CandlestickPattern {
  'wick_low' : number,
  'patternType' : string,
  'wick_high' : number,
  'price' : number,
}
export interface IndicesSnapshot {
  'oi' : bigint,
  'lastPrice' : number,
  'name' : string,
  'volume' : bigint,
  'changePercent' : number,
}
export interface MarketSymbolData {
  'oi' : bigint,
  'lastPrice' : number,
  'volume' : bigint,
  'changePercent' : number,
  'symbol' : string,
}
export interface OptionChainEntry {
  'atm' : number,
  'ce_atm_data' : CEPEData,
  'scenarios' : ScenarioTags,
  'pe_atm_data' : CEPEData,
  'price' : PriceDetails,
  'symbol' : string,
}
export interface PriceDetails {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'vwap' : number,
}
export interface ScenarioTags {
  'trending' : boolean,
  'pcr_tested' : boolean,
  'high_oi' : boolean,
  'reversal' : boolean,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'username' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToWatchlist' : ActorMethod<[Array<[string, number]>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bearishScanner' : ActorMethod<[string], PriceDetails>,
  'bullishScanner' : ActorMethod<[string], PriceDetails>,
  'getAllCandlestickPatterns' : ActorMethod<
    [],
    Array<[string, CandlestickPattern]>
  >,
  'getAllMarketData' : ActorMethod<[], Array<PriceDetails>>,
  'getAllMarketSymbols' : ActorMethod<[], Array<MarketSymbolData>>,
  'getAllOpenHighScannerData' : ActorMethod<[], Array<[string, PriceDetails]>>,
  'getAllOpenLowScannerData' : ActorMethod<[], Array<[string, PriceDetails]>>,
  'getAllOptionChainData' : ActorMethod<[], Array<[string, OptionChainEntry]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandlestickPattern' : ActorMethod<[string], Array<CandlestickPattern>>,
  'getIndicesSnapshot' : ActorMethod<[], Array<IndicesSnapshot>>,
  'getMarketData' : ActorMethod<[string], PriceDetails>,
  'getMarketSnapshot' : ActorMethod<[], Array<MarketSymbolData>>,
  'getMarketSymbolData' : ActorMethod<[string], [] | [MarketSymbolData]>,
  'getOptionChain' : ActorMethod<[string], string>,
  'getOptionChainData' : ActorMethod<[string], OptionChainEntry>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatchlist' : ActorMethod<[], Array<[string, number]>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'refreshMarketData' : ActorMethod<[], string>,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMarketSymbolData' : ActorMethod<[string, MarketSymbolData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];