// All F&O tradeable symbols
export const FO_SYMBOLS = [
  'RELIANCE', 'TCS', 'INFY', 'HDFCBANK', 'ICICIBANK', 'SBIN', 'WIPRO', 'AXISBANK',
  'KOTAKBANK', 'LT', 'BAJFINANCE', 'MARUTI', 'TITAN', 'SUNPHARMA', 'ULTRACEMCO',
  'NESTLEIND', 'POWERGRID', 'NTPC', 'ONGC', 'COALINDIA', 'ADANIENT', 'ADANIPORTS',
  'TATAMOTORS', 'TATASTEEL', 'JSWSTEEL', 'HINDALCO', 'VEDL', 'GRASIM', 'ASIANPAINT',
  'BAJAJFINSV', 'HCLTECH', 'TECHM', 'DIVISLAB', 'DRREDDY', 'CIPLA', 'EICHERMOT',
  'HEROMOTOCO', 'APOLLOHOSP', 'BRITANNIA', 'DABUR', 'GODREJCP', 'HINDUNILVR', 'ITC',
  'MARICO', 'PIDILITIND', 'BERGEPAINT', 'COLPAL', 'EMAMILTD', 'TATACONSUM', 'UBL',
  'BAJAJ-AUTO', 'BHARTIARTL', 'LICI', 'DMART', 'ZOMATO', 'PAYTM', 'NYKAA',
  'M&M', 'TATAPOWER', 'INDUSINDBK', 'FEDERALBNK', 'BANDHANBNK', 'IDFCFIRSTB',
  'PNB', 'BANKBARODA', 'CANBK', 'UNIONBANK', 'RBLBANK', 'YESBANK',
  'HDFCLIFE', 'SBILIFE', 'ICICIPRULI', 'BAJAJHLDNG', 'MUTHOOTFIN', 'CHOLAFIN',
  'SHRIRAMFIN', 'MANAPPURAM', 'LICHSGFIN', 'RECLTD', 'PFC', 'IRFC',
  'SAIL', 'NMDC', 'MOIL', 'NATIONALUM', 'HINDCOPPER', 'RATNAMANI',
  'APLAPOLLO', 'WELCORP', 'RAMCOCEM', 'SHREECEM', 'JKCEMENT', 'HEIDELBERG',
  'AMBUJACEM', 'ACC', 'DALMIACEME', 'NUVOCO',
  'DRREDDY', 'LUPIN', 'AUROPHARMA', 'TORNTPHARM', 'ALKEM', 'IPCALAB',
  'BIOCON', 'GLENMARK', 'NATCOPHARM', 'GRANULES',
  'HAVELLS', 'VOLTAS', 'BLUESTARCO', 'WHIRLPOOL', 'CROMPTON', 'POLYCAB',
  'KEI', 'FINOLEX', 'ORIENTELEC',
  'IRCTC', 'CONCOR', 'GMRINFRA', 'ADANIPORTS', 'MAHINDCIE',
  'ZEEL', 'SUNTV', 'PVRINOX', 'INOXWIND',
  'MCDOWELL-N', 'RADICO', 'GLOBUSSPR',
  'TRENT', 'ABFRL', 'PAGEIND', 'MANYAVAR', 'VEDANT',
  'NAUKRI', 'JUSTDIAL', 'INDIAMART', 'AFFLE',
  'PERSISTENT', 'COFORGE', 'MPHASIS', 'LTTS', 'KPITTECH',
  'DIXON', 'AMBER', 'KAYNES', 'SYRMA',
  'DEEPAKNTR', 'AAVAS', 'HOMEFIRST', 'APTUS',
  'LALPATHLAB', 'METROPOLIS', 'THYROCARE',
  'CLEAN', 'GREENPANEL', 'CENTURYPLY',
  'ASTRAL', 'SUPREMEIND', 'FINOLEX',
  'CAMS', 'CDSL', 'BSE', 'MCX',
  'ANGELONE', 'IIFL', '360ONE',
  'DELHIVERY', 'BLUEDART', 'GATI',
  'HAPPSTMNDS', 'TANLA', 'ROUTE',
  'LATENTVIEW', 'MASTEK', 'BIRLASOFT',
];

// Legacy alias kept for backward compatibility
export const STOCKS = FO_SYMBOLS;

export const NEWS_HEADLINES = [
  'NIFTY hits all-time high, banking sector leads rally',
  'FII net buying crosses ₹2,000 crore mark today',
  'RBI holds rates steady, focus on inflation control',
  'RELIANCE announces green energy partnership worth ₹75,000 Cr',
  'IT sector faces margin pressure, TCS dips 2% on weak guidance',
  'Auto sales data shows robust EV demand, Tata Motors surges',
  'Crude oil prices stabilize below $80/barrel, OMCs rally',
  'Mid-cap index outperforms benchmarks for third consecutive week',
  'SEBI tightens F&O rules, lot sizes to increase from next expiry',
  'Budget expectations drive infrastructure stocks higher',
  'Global cues positive as US Fed signals rate pause',
  'Pharma sector gains on strong export data from DGCI',
  'Metal stocks rally on China stimulus hopes',
  'HDFC Bank Q3 results beat estimates, NII up 12% YoY',
  'Nifty Bank crosses 49,000 for the first time',
];
